version: '3.8'
services:
  app:
    build: .
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_NAME=app_db
    networks:
      - app_net
    deploy:
      replicas: 3
    volumes:
      - app_logs:/app/logs

  nginx:
    image: arm64v8/nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - app_net

  db:
    image: arm64v8/mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: app_db
    networks:
      - app_net
    volumes:
      - db_data:/var/lib/mysql
      - db_logs:/var/log/mysql

networks:
  app_net:

volumes:
  app_logs:
  db_data:
  db_logs:
